# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build
  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

  only:
    - master
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: always

build:
  stage: deploy
  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker-compose up -d --quiet-pull
    # - docker image prune -f
  except:
    - master
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: always
