dist: xenial
sudo: true
env:
  global:
    - TRAVIS_SECURE_ENV_VARS=true
    - DEBUG=electron-builder

matrix:
  include:
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "8"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      sudo: required
      services: docker
      language: generic

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - npm install
before_script:
  - npm run test
  - npm run mocha
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        -e TRAVIS=$TRAVIS \
        -e TRAVIS_SECURE_ENV_VARS=$TRAVIS_SECURE_ENV_VARS \
        -e GH_TOKEN=${GH_TOKEN} \
        -v $(pwd):/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        bash -c "
          npm install \
          && npm run electron:linux && npm run electron:windows "
    else
      # Code signing for macOS is not available in Docker, so we build on macOS.
      npm run electron:mac
    fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
fhdfjhjh@8r8r78bcbf!@&*