version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 13307:3306
    environment:
      DB_HOST: mysql
      MYSQL_DATABASE: flipper
      MYSQL_USER: flipper
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: flipper
    volumes:
      - ./:/var/www/html
    ports:
      - 8009:80
    environment:
      APP_DEBUG: "true"
    links:
      - mysql
  # composer:
  #   restart: always
  #   image: composer/composer:php7
  #   volumes:
  #     - ./:/var/www/html
  #   command: docker-compose exec composer install
