name: enexus
description: An inventory system for all.

version: 0.1.0

environment:
  sdk: '>=2.0.0 <3.0.0'
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: '>=1.10.2-pre.54'

dependencies:
  flutter:
    sdk: flutter
  bloc_pattern:
  rxdart:
  http: ^0.12.0+2
  moor_flutter: ^1.6.0
  # For the UI
  provider: ^3.0.0+1
  flutter_slidable: ^0.5.3
  flutter_material_color_picker: ^1.0.3
  flutter_svg: ^0.14.0
  flutter_bloc: ^0.20.0
  equatable: ^0.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  scrollable_bottom_sheet: ^0.2.1
  #TODO: need to dig deeper on the bellow package it is not stable at all.
  flutter_realm: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^1.6.0+2
  build_runner:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/cm1.jpeg
    - assets/cm2.jpeg
    - assets/cm3.jpeg
    - assets/cm4.jpeg
    - assets/cm5.jpeg
    - assets/cm6.jpeg
    - assets/cm7.jpeg
    - assets/cm8.jpeg
    - assets/cm9.jpeg
    - assets/cm0.jpeg
    - assets/logo.png
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900