  type: app
  base: "flipper"
  name: flipper
  version: '1.1.41' # just for humans, typically '1.2+git' or '1.3.2'
  summary: A Point of sale app much like square app # 79 char long summary
  description: |
    The point of sale application and stock management.

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
